### ISSUE TITLE
No Module named 'openai'

### ISSUE THREAD

**Issue by jsbrown88** [smol-ai/developer#117]
When running the latest update - 7 hours ago from writing - I see installation instructions have changed since last night :D 

no more pip install -r requirements.txt but rather poetry install. Done all that and then when I come to run any type of promt I get the following 

"PS D:\Development\SMOLAI\developer> poetry install
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: smol_dev (0.0.3)
PS D:\Development\SMOLAI\developer> python main.py a HTML/JS/CSS Tic Tac Toe Game
Traceback (most recent call last):
  File "D:\Development\SMOLAI\developer\main.py", line 3, in <module>
    from smol_dev.prompts import plan, specify_file_paths, generate_code_sync     
  File "D:\Development\SMOLAI\developer\smol_dev\__init__.py", line 1, in <module>
    from smol_dev.prompts import *
  File "D:\Development\SMOLAI\developer\smol_dev\prompts.py", line 6, in <module> 
    import openai
ModuleNotFoundError: No module named 'openai'
PS D:\Development\SMOLAI\developer> "

Still a bit of a noob but im guessing the poetry install , allthough confirming that openai is installed doesnt find it.

Great fan. Thanks so much for wat you are doing.

**Comment by joelmgallant** [comment]
You may need to prefix commands with `poetry run` 
ie: `poetry run python main.py --prompt "a test case"`

or open a `poetry shell` to activate the environment

**Comment by Chaitanyjanmale2** [comment]
Traceback (most recent call last):
  File "E:\SMOLAI\developer\main.py", line 3, in <module>
    from smol_dev.prompts import plan, specify_file_paths, generate_code_sync
  File "E:\SMOLAI\developer\smol_dev\__init__.py", line 1, in <module>
    from smol_dev.prompts import *
  File "E:\SMOLAI\developer\smol_dev\prompts.py", line 7, in <module>
    from openai_function_call import openai_function
ModuleNotFoundError: No module named 'openai_function_call'

pip show openai 
validates that openai is available on my system
but shows the above error as well


please assists!!!

**Comment by RohanSangle** [comment]
error got after running "poetry run python main_no_modal.py " "prompt.md"
(in prompt.md I had written ' a HTML/JS/CSS Tic Tac Toe Game ' )

==>
hi its me, �🐣the smol develope🐣🐣! you said you wan
a HTML/JS/CSS Tic Tac Toe Game
Traceback (most recent call last):
  File "C:\Users\Kiran\Desktop\chrome extension\developer\v0\main_no_modal.py", line 232, in <module>
    main(prompt, directory, file)
  File "C:\Users\Kiran\Desktop\chrome extension\developer\v0\main_no_modal.py", line 122, in main
    filepaths_string = generate_response(
                       ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kiran\Desktop\chrome extension\developer\v0\main_no_modal.py", line 10, in generate_response
    import openai
ModuleNotFoundError: No module named 'openai'

please help!

**Comment by szczesnypawel** [comment]
> error got after running "poetry run py main.py "a test case""
> 
> ==> Traceback (most recent call last): File "E:\SMOLAI\developer\main.py", line 3, in from smol_dev.prompts import plan, specify_file_paths, generate_code_sync File "E:\SMOLAI\developer\smol_dev__init__.py", line 1, in from smol_dev.prompts import * File "E:\SMOLAI\developer\smol_dev\prompts.py", line 7, in from openai_function_call import openai_function ModuleNotFoundError: No module named 'openai_function_call'
> 
> pip show openai validates that openai is available on my system but shows the above error as well
> 
> please assists!!!



> error got after running "poetry run py main.py "a test case""
> 
> ==> Traceback (most recent call last): File "E:\SMOLAI\developer\main.py", line 3, in from smol_dev.prompts import plan, specify_file_paths, generate_code_sync File "E:\SMOLAI\developer\smol_dev__init__.py", line 1, in from smol_dev.prompts import * File "E:\SMOLAI\developer\smol_dev\prompts.py", line 7, in from openai_function_call import openai_function ModuleNotFoundError: No module named 'openai_function_call'
> 
> pip show openai validates that openai is available on my system but shows the above error as well
> 
> please assists!!!

I am having the same issue  - openai_function_call cannot be imported. I've installed everything via poetry. pip list shows openai_function_call on the list. I cannot import it via python interactive shell either. 

Any hints?

**Comment by EmpathicSage** [comment]
I also received the same error "No module named 'openai_function_call" when first trying the project and resolved it.

NOTE: When we report bugs as a community, let's take the time to include the environment information to reproduce the bug, such as the name and version of the application, the version of the operating system, execution switches, etc. This aids in reproducing the error and understanding the specific circumstances. Otherwise, the messages may not be actionable.

# Environment

- Windows 11 Pro 21H2 Build 22000.2295
- i7-6800K CPU
- 128 GiB RAM
- NVIDIA GeForce 1080Ti GTX 
- Git Bash version 2.41.0.2 (https://gitforwindows.org/)
- pip 23.1.2 from C:\Python311\Lib\site-packages\pip (python 3.11)

# Steps to Reproduce

1. **Launch the program "git-bash.exe" from the Windows GUI**
2. `mkdir -p ~/git`
3. `cd ~/git`
4. `git clone https://github.com/smol-ai/developer.git`
5. `cd developer`
6. `pip install poetry`
7. `poetry install`
8. `py main.py --prompt "Create a bash script that plays blackjack interactively with the user."`
9. **ERROR: No module named 'openai_function_call'**

# Steps to Resolve

1. `poetry shell`
2. `export OPENAI_API_KEY=sk-XXXXX` # add your Open AI API key
3. `py main.py --prompt "Create a bash script that plays blackjack interactively with the user."
4. **SUCCESS: file written to generated/blackjack.sh and generated/shared_deps.md**
