### ISSUE TITLE
SyntaxError: invalid decimal literal 

### ISSUE THREAD

**Issue by hawkmax** [smol-ai/developer#45]
I keep running into this error. Any Idea what this means ?

Traceback (most recent call last):
  File "C:\Users\User\Desktop\developer\main_no_modal.py", line 244, in <module>
    main(prompt, directory, file)
  File "C:\Users\User\Desktop\developer\main_no_modal.py", line 141, in main
    list_actual = ast.literal_eval(filepaths_string)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\ast.py", line 64, in literal_eval
    node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<unknown>", line 18
    - /database/migrations/2021_01_01_create_users_table.php
                                     ^
SyntaxError: invalid decimal literal

**Comment by stagsz** [comment]
Getting the same results.

**Comment by swyxio** [comment]
sorry about that - this is the api returning non json. its a prompt issue. we will improve this

**Comment by dangell7** [comment]
same error.

adding the below to the prompt solved this.

```
Dont add "-" to the output.
```
