### ISSUE TITLE
I getting error any time using modal (i have the access)

### ISSUE THREAD

**Issue by Mpiffer** [smol-ai/developer#51]
PS F:\WPPTESTS\developer-main> modal run main.py --prompt app dashboard
Usage: modal run main.py [OPTIONS]
Try 'modal run main.py --help' for help.
╭─ Error ────────────────────────────────────────────────────────╮│ Got unexpected extra argument (dashboard)                      │╰────────────────────────────────────────────────────────────────╯PS F:\WPPTESTS\developer-main> modal run main.py --prompt "app dashboard"
✓ Initialized. View app at 
https://modal.com/apps/ap-rszKOu9o7GTMUrv34n8yYs
✓ Created objects.
├── 🔨 Created generate_response.
├── 🔨 Created mount F:\WPPTESTS\developer-main\main.py
└── 🔨 Created generate_file.
hi its me, 🐣the smol developer🐣! you said you wanted:
app dashboard
89 tokens in prompt: You are an AI developer who is trying to write a p
2 tokens in prompt: app dashboard
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 330, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 403, in call_function_sync
    res = fun(*args, **kwargs)
  File "/root/main.py", line 52, in generate_response
    response = openai.ChatCompletion.create(**params)
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 230, in request
    resp, got_stream = self._interpret_response(result, stream)   
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 624, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 687, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: <empty message>
89 tokens in prompt: You are an AI developer who is trying to write a p
2 tokens in prompt: app dashboard
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 330, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 403, in call_function_sync
    res = fun(*args, **kwargs)
  File "/root/main.py", line 52, in generate_response
    response = openai.ChatCompletion.create(**params)
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 230, in request
    resp, got_stream = self._interpret_response(result, stream)   
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 624, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 687, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: <empty message>
89 tokens in prompt: You are an AI developer who is trying to write a p
2 tokens in prompt: app dashboard
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 330, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 403, in call_function_sync
    res = fun(*args, **kwargs)
  File "/root/main.py", line 52, in generate_response
    response = openai.ChatCompletion.create(**params)
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 230, in request
    resp, got_stream = self._interpret_response(result, stream)   
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 624, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 687, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: <empty message>
89 tokens in prompt: You are an AI developer who is trying to write a p
2 tokens in prompt: app dashboard
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 330, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 403, in call_function_sync
    res = fun(*args, **kwargs)
  File "/root/main.py", line 52, in generate_response
    response = openai.ChatCompletion.create(**params)
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 230, in request
    resp, got_stream = self._interpret_response(result, stream)   
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 624, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 687, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: <empty message>
Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 1699, in print      
    extend(render(renderable, render_options))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 1335, in render     
    yield from self.render(render_output, _options)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 1331, in render     
    for render_output in iter_render:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\constrain.py", line 29, in __rich_console__
    yield from console.render(self.renderable, child_options)     
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 1331, in render     
    for render_output in iter_render:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\panel.py", line 220, in __rich_console__
    lines = console.render_lines(renderable, child_options, style=style)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 1371, in render_lines
    lines = list(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\segment.py", line 292, in split_and_crop_lines
    for segment in segments:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 1331, in render     
    for render_output in iter_render:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\padding.py", line 97, in __rich_console__
    lines = console.render_lines(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 1371, in render_lines
    lines = list(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\segment.py", line 292, in split_and_crop_lines
    for segment in segments:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 1335, in render     
    yield from self.render(render_output, _options)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 1331, in render     
    for render_output in iter_render:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\syntax.py", line 611, in __rich_console__
    segments = Segments(self._get_syntax(console, options))       
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\segment.py", line 668, in __init__    
    self.segments = list(segments)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\syntax.py", line 639, in _get_syntax  
    text = self.highlight(processed_code, self.line_range)        
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\syntax.py", line 512, in highlight    
    text.append_tokens(tokens_to_spans())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\text.py", line 991, in append_tokens  
    for content, style in tokens:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\syntax.py", line 498, in tokens_to_spans
    _token_type, token = next(tokens)
KeyboardInterrupt

Original exception was:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Scripts\modal.exe\__main__.py", line 7, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\modal\__main__.py", line 6, in main        
    entrypoint_cli()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__     
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\typer\core.py", line 778, in main
    return _main(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\typer\core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1657, in invoke       
    return _process_result(sub_ctx.command.invoke(sub_ctx))       
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1657, in invoke       
    return _process_result(sub_ctx.command.invoke(sub_ctx))       
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke       
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke        
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\click\decorators.py", line 26, in new_func 
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\modal\cli\run.py", line 116, in f
    func(*args, **kwargs)
  File "F:\WPPTESTS\developer-main\main.py", line 125, in main
    filepaths_string = generate_response.call(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\synchronicity\synchronizer.py", line 497, in proxy_method
    return wrapped_method(instance, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\synchronicity\combined_types.py", line 26, 
in __call__
    raise uc_exc.exc from None
  File "<ta-hJgFeRqn4qUfu8KKPQV44E>:/root/main.py", line 52, in generate_response
  File "<ta-hJgFeRqn4qUfu8KKPQV44E>:/usr/local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
  File "<ta-hJgFeRqn4qUfu8KKPQV44E>:/usr/local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
  File "<ta-hJgFeRqn4qUfu8KKPQV44E>:/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 230, in request
  File "<ta-hJgFeRqn4qUfu8KKPQV44E>:/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 624, in _interpret_response
  File "<ta-hJgFeRqn4qUfu8KKPQV44E>:/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 687, in _interpret_response_line
openai.error.AuthenticationError: <empty message>
PS F:\WPPTESTS\developer-main> modal run main.py --prompt prompt2.md

**Comment by swyxio** [comment]
did you copy the .env file and put in your api key?
