### ISSUE TITLE
Traceback errors and KeyError

### ISSUE THREAD

**Issue by TheEvulKing** [smol-ai/developer#85]
Hi guys! I'm still very new to coding, so please be patient with me. I followed all of the instructions to run Smol-ai and put my api key from openai into the area: OPENAI_API_KEY=  

After prompting Smol-ai It tells me: 

>> 
hi its me, 🐣the smol developer🐣! you said you wanted: "My_Prompt" in text

But then I get the following errors

Traceback (most recent call last):
  File "C:\A.I\Smol Ai Developer\developer\main_no_modal.py", line 230, in <module>
    main(prompt, directory, file)
  File "C:\A.I\Smol Ai Developer\developer\main_no_modal.py", line 121, in main
    filepaths_string = generate_response(
  File "C:\A.I\Smol Ai Developer\developer\main_no_modal.py", line 26, in generate_response
    openai.api_key = os.environ["OPENAI_API_KEY"]
  File "C:\Users\Zove\AppData\Local\Programs\Python\Python310\lib\os.py", line 680, in __getitem__    
    raise KeyError(key) from None
KeyError: 'OPENAI_API_KEY'

I signed up for Modal but am still on the waitlist. So I'm using the: python main_no_modal.py "   " --model=gpt-4

I also have access to gpt-4 through the paid subscription as well

Any help would be appreciated and thanks!! :D

**Comment by therealron** [comment]
I'm getting the same error. Did you find out what was wrong?

**Comment by boylucky** [comment]
I solved the problem with KeyError: 'OPENAI_API_KEY' mentioned above by adding the API key directly to main_no_modal.py on line 26: openai.api_key = "paste here your api key"
Anyway then I am getting another error in the main_no_modal.py:

Note: The user may choose to name the files differently or store them in a different directory.
Traceback (most recent call last):
  File "C:\Github\developer\main_no_modal.py", line 230, in <module>
    main(prompt, directory, file)
  File "C:\Github\developer\main_no_modal.py", line 135, in main
    list_actual = ast.literal_eval(filepaths_string)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boylucky\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 64, in literal_eval
    node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boylucky\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<unknown>", line 1
    I assume you want me to generate the filepaths for creating a python script that counts from 100 to 1. Here are the filepaths:
      ^^^^^^
SyntaxError: invalid syntax

Any help will be appreciated. By the way I am using the python virtual environments instead of modal.

Thanks in advance.
